Repository THE-FIRST-DANCE/the-first, pull requests merged in 2023-12, with the labels that each got.

#17 로그인 로직 추가, 프로필 페이지 추가, 일부 로직과 컴포넌트 리팩토링
  index.html
  public/logo.svg
  src/App.tsx
  src/assets/icons/emoji.tsx
  src/assets/icons/plus.tsx
  src/axios.ts
  src/components/Left/CreatePostExtend.tsx
  src/components/Left/ImageSlider.tsx
  src/components/Left/InputArea.tsx
  src/components/Left/SearchExtend.tsx
  src/components/Left/SearchItem.tsx
  src/components/Left/Sidebar.tsx
  src/components/Left/index.tsx
  src/components/Main/MainCard.tsx
  src/components/Main/index.tsx
  src/components/Profile/MyProfile.tsx
  src/components/Profile/ProfilePosts.tsx
  src/components/Profile/index.tsx
  src/components/common/Line.tsx
  src/components/common/NotFound.tsx
  src/components/common/Skeleton.tsx
  src/contexts/LogonUser.ts
  src/hooks/useStayLogin.ts
  src/interfaces/auth.interface.ts
  src/interfaces/post.interface.ts
  src/interfaces/thumbsnap.interface.ts
  src/interfaces/user.interface.ts
  src/pages/login.tsx
  src/pages/logout.tsx
  src/pages/notfound.tsx
  src/pages/profile.tsx
  src/pages/redirect.tsx
  src/pages/register.tsx
  src/router.tsx
  src/services/auth.service.ts
  src/services/posts.service.ts
  src/services/tags.service.ts
  src/services/users.service.ts
  src/styles/GlobalStyle.ts
  src/utils/auth.ts
  src/utils/expire.ts
Labels: ✨ feat, 💄 UI, 📬 API, 🔨 Refactor

#21 로그인 회원가입 페이지 form 수정, 유저 아바타 컴포넌트 적용
  src/components/Input.tsx
  src/components/Left/CreatePostExtend.tsx
  src/components/Left/Sidebar.tsx
  src/components/Main/MainCard.tsx
  src/components/Profile/MyProfile.tsx
  src/components/common/UserAvatar.tsx
  src/pages/home.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/utils/dateFormatter.ts
  src/utils/formatter.ts
Labels: 🔨 Chore, ✨ feat

#25 ErrorMsg validation 작성, 빠뜨린 UserAvatar 적용
  src/App.tsx
  src/components/Input.tsx
  src/components/Left/SearchItem.tsx
  src/components/Left/Sidebar.tsx
  src/components/Main/MainCard.tsx
  src/components/Profile/MyProfile.tsx
  src/components/common/ErrorMsg.tsx
  src/components/common/UserAvatar.tsx
  src/interfaces/user.interface.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/services/auth.service.ts
  src/services/users.service.ts
  src/services/validate.service.ts
  src/utils/formatter.ts
Labels: 🔨 Chore, ✨ feat, 💄 UI

#28 MainCard 일부 스타일 수정 및 데이터 추가
  server/db.json
  src/components/Main/MainCard.tsx
Labels: 💄 UI

#32 스토리 crud 기능 추가
  package.json
  src/components/Left/CreatePostExtend.tsx
  src/components/Left/ImageModal.tsx
  src/components/Main/Story.tsx
  src/components/Main/StoryModal.tsx
  src/components/Story/index.tsx
  src/interfaces/story.interface.ts
  src/pages/story.tsx
  src/services/imageSearch.service.ts
  yarn.lock
Labels: ✨ feat

#34 프로필 게시물에 사용자 정보 추가, 스토리 내 이미지 fit 수정
  src/components/Main/StoryModal.tsx
  src/components/Profile/Modal.tsx
  src/components/Profile/ProfilePosts.tsx
  src/components/Profile/index.tsx
  src/components/Story/index.tsx
  src/services/posts.service.ts
Labels: 🐛 Bug, ✨ feat, 💄 UI

#35 폰트 수정, 콘솔로깅 삭제
  server/db.json
  src/components/Main/index.tsx
  src/components/Profile/Modal.tsx
Labels: 🐛 Bug, 💄 UI

#38 프로젝트 설명 작성중
  README.md
Labels: 📝 docs
